source 'https://rubygems.org'

  gem 'rails', '3.2.11'

  gem 'pg'

  group :development do
    gem 'haml-rails', '>= 0.3.5'
    gem 'rspec-rails', '>= 2.12.2'
    gem 'factory_girl_rails', '>= 4.2.0'
    gem 'quiet_assets', '>= 1.0.1'
    gem 'awesome_print'
  end

  group :assets do
    gem 'sass-rails',   '~> 3.2.3'
    gem 'coffee-rails', '~> 3.2.1'

    # See https://github.com/sstephenson/execjs#readme for more supported runtimes
    # gem 'therubyracer', :platforms => :ruby
    gem 'uglifier', '>= 1.0.3'
   end

  group :test do
    gem 'rspec-rails', '>= 2.12.2'
    gem 'database_cleaner', '>= 0.9.1'
    gem 'capybara', '>= 2.0.2'
    gem 'factory_girl_rails', '>= 4.2.0'
  end

  gem 'jquery-rails'

  gem 'haml', '>= 3.1.7'
  gem 'devise', '>= 2.2.3'
  gem 'rails_admin'
  gem 'cancan'

  gem 'google-webfonts'
  gem 'simple_form'

  # If we need an uploader
  # gem 'mini_magick'
  # gem 'fog'
  # gem 'carrierwave'

  # For Graphs
  # gem 'nvd3-rails'

  # For scheduling
  # gem 'resque'
  # gem 'resque-scheduler', :require => 'resque_scheduler'


  # Choose one - Rest client default
  # gem 'rest-client'
  # gem 'httparty'

  # BOOTSTRAP FRONT END STACK - DEFAULT
  gem 'therubyracer'
  gem 'less-rails'
  gem 'twitter-bootstrap-rails'
  gem 'font-awesome-rails'

  # ZURB FOUNDATION STACK
  # gem 'compass-rails'
  # gem 'zurb-foundation'
  # gem 'foundation-icons-sass-rails'

  # Notifier
  # gem 'alertify-rails'
  # gem 'vex_rails'

  # MORE UI/UX STUFF
  #
  # gem 'ladda_on_rails'
  # gem 'nprogress-rails'
  # gem 'animate-rails'
  # gem 'spacers_and_dividers'

  # To use ActiveModel has_secure_password
  # gem 'bcrypt-ruby', '~> 3.0.0'

  # To use Jbuilder templates for JSON
  # gem 'jbuilder'

  # Use unicorn as the app server
  # gem 'unicorn'

  # Deploy with Capistrano
  # gem 'capistrano'

  # To use debugger
  # gem 'debugger'
